JobSocialPoster/JobSocialPoster.WebUI/Controllers/ProfileManagerController.cs
 using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CsvHelper;
using JobSocialPoster.Core.Contracts;
using JobSocialPoster.Core.Models;
using JobSocialPoster.Core.ViewModels;
using JobSocialPoster.DataAccess.InMemory;


namespace JobSocialPoster.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProfileManagerController : Controller
    {
        IRepository<Profile> context;
        IRepository<ProfileCategory> profileCategories;
        IRepository<Post> pcontext;

        public ProfileManagerController(IRepository<Profile> profileContext, IRepository<ProfileCategory> profileCategoryContext, IRepository<Post> postContext)
        {
            context = profileContext;
            profileCategories = profileCategoryContext;
            pcontext = postContext;
        }

        
        public ActionResult Index(string message, string sortOrder)
        {
            List<Profile> profiles;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CategorySortParm = sortOrder == "category" ? "category_desc" : "category";

            switch (sortOrder)
            {
                case "name_desc":
                    profiles = context.Collection().OrderByDescending(p => p.Name).ToList();
                    break;
                case "category":
                    profiles = context.Collection().OrderBy(p => p.Category).ToList();
                    break;
                case "category_desc":
                    profiles = context.Collection().OrderByDescending(p => p.Category).ToList();
                    break;
                default:
                    profiles = context.Collection().ToList();
                    break;
            }

            ViewBag.message = Request.QueryString["message"];

            return View(profiles);

        }


        public ActionResult Create()
        {
            ProfileManagerViewModel viewModel = new ProfileManagerViewModel();

            viewModel.Profile = new Profile();
            viewModel.ProfileCategories = profileCategories.Collection();
            return View(viewModel);
        }

        public ActionResult Import(string Id)
        {
            Profile profile = context.Find(Id);

            if (profile == null)
            {
                return HttpNotFound();
            }
            else
            {
                ProfileManagerViewModel viewModel = new ProfileManagerViewModel();
                viewModel.Profile = profile;
                viewModel.ProfileCategories = profileCategories.Collection();

                if (profile.ImportCsv == false)
                {
                        //return RedirectToAction("ImportDenied");
                        ViewBag.ImportCheck = "<h4 class=\"text-danger\">Automatyczny import jest wyłączony, czy mimo to chcesz kontynuować?</h4>";
                        return View(viewModel);
                }

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Import(Profile profile, string Id, Post post)
        {
            Profile profileToImport = context.Find(Id);

            if (profileToImport == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(profile);
                }

                profileToImport.ImportCsv = false;
                
                IList<Post> posts;

                var streamreader = new StreamReader(Server.MapPath("//Content//ImportFiles//") + profileToImport.File);
                var reader = new CsvReader(streamreader, CultureInfo.InvariantCulture);

                reader.Configuration.HeaderValidated = null;
                posts = reader.GetRecords<Post>().ToList();
                

                foreach (var p in posts)
                {
                    p.Profile = profileToImport.Name;
                    pcontext.Insert(p);
                }

                pcontext.Commit();
                context.Commit();

                var message = "Posty zostały zaimportowane";
                return RedirectToAction("Index", new { message });
            }

        }

        public ActionResult ImportAllCsv()
        {
            List<Profile> profilesToImport = context.Collection().Where(p => (p.ImportCsv == true) && (p.IsActive == true)).ToList();

            //ViewBag.message = Request.QueryString["message"];

            return View(profilesToImport);

        }

        [HttpPost]
        public ActionResult ImportAllCsv(Profile profile, string Id, Post post)
        {
            //Profile profileToImport = context.Find(Id);
            List<Profile> profilesToImport = context.Collection().Where(p => (p.ImportCsv == true) && (p.IsActive == true)).ToList();
            
            if (profilesToImport == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(profile);
                }

                foreach (var p in profilesToImport)
                {
                    p.ImportCsv = false;

                    IList<Post> posts;

                    var streamreader = new StreamReader(Server.MapPath("//Content//ImportFiles//") + p.File);
                    var reader = new CsvReader(streamreader, CultureInfo.InvariantCulture);

                    reader.Configuration.HeaderValidated = null;
                    posts = reader.GetRecords<Post>().ToList();


                    foreach (var pp in posts)
                    {
                        pp.Profile = p.Name;
                        pcontext.Insert(pp);
                    }
                }

                pcontext.Commit();
                context.Commit();

                var message = "Posty aktywnych profili zostały zaimportowane";
                return RedirectToAction("Index", new { message });
            }

        }

        [HttpPost]
        public ActionResult Create(Profile profile, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(profile);
            }
            else
            {

                if (file != null)
                {

                    profile.File = file.FileName;
                    file.SaveAs(Server.MapPath("//Content//ImportFiles//") + profile.File);

                }
                context.Insert(profile);
                context.Commit();

                var message = "Utworzono nowy profil" + profile.Name;
                return RedirectToAction("Index", new { message });
            }
        }

        public ActionResult Edit(string Id)
        {
            Profile profile = context.Find(Id);

            if (profile == null)
            {
                return HttpNotFound();
            }
            else
            {
                ProfileManagerViewModel viewModel = new ProfileManagerViewModel();
                viewModel.Profile = profile;
                viewModel.ProfileCategories = profileCategories.Collection();
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Edit(Profile profile, string Id, HttpPostedFileBase file)
        {
            Profile profileToEdit = context.Find(Id);

            if (profileToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(profile);
                }
                
                if (file != null)
                {
                    profileToEdit.File = file.FileName;
                    file.SaveAs(Server.MapPath("//Content//ImportFiles//") + profileToEdit.File);
                }

                profileToEdit.Category = profile.Category;
                profileToEdit.ImportCsv = profile.ImportCsv;
                profileToEdit.IsActive = profile.IsActive;
                profileToEdit.Name = profile.Name;
                profileToEdit.SocialpilotId = profile.SocialpilotId;
                profileToEdit.Url = profile.Url;
                profileToEdit.Weight = profile.Weight;

                context.Commit();

                return RedirectToAction("Index");
            }

        }

        public ActionResult Delete(string Id)
        {
            Profile profileToDelete = context.Find(Id);

            if (profileToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(profileToDelete);
            }

        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            Profile profileToDelete = context.Find(Id);

            if (profileToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                context.Delete(Id);
                context.Commit();
                return RedirectToAction("Index");
            }
        }
    }
}

JobSocialPoster/JobSocialPoster.WebUI/Views/ProfileManager/Create.cshtml
@model JobSocialPoster.Core.ViewModels.ProfileManagerViewModel

@{
    ViewBag.Title = "Utwórz nowy profil";
}

<h2>Utwórz nowy profil</h2>


@using (Html.BeginForm("Create","ProfileManager", FormMethod.Post, new {encType="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.SocialpilotId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.SocialpilotId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.SocialpilotId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Profile.IsActive)
                    @Html.ValidationMessageFor(model => model.Profile.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.ImportCsv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Profile.ImportCsv)
                    @Html.ValidationMessageFor(model => model.Profile.ImportCsv, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Profile.Category, new SelectList(Model.ProfileCategories, "Name", "Name"), htmlAttributes : new { @class = "form-control" } )
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz profil" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobSocialPoster/JobSocialPoster.WebUI/Views/ProfileManager/Delete.cshtml
@model JobSocialPoster.Core.Models.Profile

@{
    ViewBag.Title = "Usuń profil";
}

<h2>Usuń profil</h2>

<h3>Czy na pewno chcesz usunąć profil?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.File)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SocialpilotId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SocialpilotId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImportCsv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImportCsv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót", "Index")
        </div>
    }
</div>

JobSocialPoster/JobSocialPoster.WebUI/Views/ProfileManager/Edit.cshtml
@model JobSocialPoster.Core.ViewModels.ProfileManagerViewModel

@{
    ViewBag.Title = "Edycja profilu";
}

<h2>Edytuj profil</h2>


@using (Html.BeginForm("Edit","ProfileManager", FormMethod.Post, new {encType="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Profile.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
                Aktualny plik: <a href="~/Content/ImportFiles/@Model.Profile.File">@Model.Profile.File</a>
            </div>
            
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.SocialpilotId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.SocialpilotId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.SocialpilotId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Profile.IsActive)
                    @Html.ValidationMessageFor(model => model.Profile.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profile.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profile.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.ImportCsv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Profile.ImportCsv)
                    @Html.ValidationMessageFor(model => model.Profile.ImportCsv, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Profile.Category, new SelectList(Model.ProfileCategories, "Name", "Name"), htmlAttributes: new { @class = "form-control" } )
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobSocialPoster/JobSocialPoster.WebUI/Views/ProfileManager/Import.cshtml
@model JobSocialPoster.Core.ViewModels.ProfileManagerViewModel

@{
    ViewBag.Title = "Import";
}

<h2>Import</h2>
@Html.Raw(ViewBag.ImportCheck)

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>
            Importuj posty z pliku CSV dla Profilu: <a href="@Model.Profile.Url">@Model.Profile.Name</a>
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Profile.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Profile.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="padding-top:7px;">
                Aktualny plik: <a href="~/Content/ImportFiles/@Model.Profile.File">@Model.Profile.File</a>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Importuj posty" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobSocialPoster/JobSocialPoster.WebUI/Views/ProfileManager/ImportAllCsv.cshtml
@model IEnumerable<JobSocialPoster.Core.Models.Profile>

@{
    ViewBag.Title = "ImportAllCsv";
}

<h2>Importuj posty z CSV</h2>
<p>Importuj posty z plików CSV przypisanych do wszystkich aktywnych profili społecznościowych.</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Importuj posty" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.File)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SocialpilotId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImportCsv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.File)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SocialpilotId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                <a href="@Html.Raw(item.Url)">Zobacz profil &raquo;</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImportCsv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
        </tr>
    }

</table>

JobSocialPoster/JobSocialPoster.WebUI/Views/ProfileManager/Index.cshtml
@model IEnumerable<JobSocialPoster.Core.Models.Profile>

@{
    ViewBag.Title = "Zarządzaj profilami";
}

<h2>Zarządzaj profilami</h2>
@Html.Raw(ViewBag.message)
<p>
    @Html.ActionLink("Dodaj nowy profil", "Create")
</p>

<table class="table">
    <tr>
        <th>

            @Html.DisplayNameFor(model => model.Name) @Html.ActionLink(" ", "Index", new { sortOrder = ViewBag.NameSortParm }, new { @class = "glyphicon glyphicon-sort" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.File)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SocialpilotId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImportCsv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category) @Html.ActionLink(" ", "Index", new { sortOrder = ViewBag.CategorySortParm }, new { @class = "glyphicon glyphicon-sort" })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a id="import-file" href="~/Content/ImportFiles/@item.File">@Html.DisplayFor(modelItem => item.File)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SocialpilotId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                <a href="@Html.Raw(item.Url)">Zobacz profil &raquo;</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImportCsv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.ActionLink("Edycja", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Import", "Import", new { id = item.Id }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>